spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: data
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/security
    username: postgres
    password: root

